[package]
name = "cauldron"
version = "0.1.0"
authors = ["Alessio Biancalana <alessio@dottorblaster.it>"]
edition = "2021"
publish = false

[profile.release]
lto = true

[dependencies]
article_scraper = { git = "https://gitlab.com/news-flash/article_scraper.git" }
gettext-rs = { version = "0.7", features = ["gettext-system"] }
relm4 = { version = "0.9.1", features = ["libadwaita", "gnome_47"] }
tracing = "0.1.37"
tracing-subscriber = "0.3"
anyhow = "1.0.94"
oauth2 = "4.4.2"
open = "5.3.1"
reqwest = { version = "0.12.9", features = ["blocking", "json"] }
serde = "1.0.215"
serde_json = "1.0.133"
url = "2.5.2"
webkit6 = "0.4.0"
